import React from 'react';
import Head from 'next/head';
// import MainHeader from '../MainHeader/MainHeader';
import TracksWithFilters from '@/components/content/TracksWithFilters/TracksWithFilters';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                {/* <MainHeader/> */}
                <TracksWithFilters></TracksWithFilters>
                {children}
            </main>
        </>
    )
}

export default Layout;