import React from 'react';
import Head from 'next/head'

const Layout = ({children}) => {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {
                /* <script type="text/plain" data-cookiecategory="analytics_storage">
                {`
                (function(w,d,s,l,i){
                    w[l]=w[l]||[];
                    w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
                    var f=d.getElementsByTagName(s)[0],
                    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;
                    j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
                    f.parentNode.insertBefore(j,f)
                })(window,document,'script','dataLayer','GTM-T4TSM6F')  
                `}
                </script> */}
            </Head>
            <main>
                {children}
            </main>
        </>    
    )
    
    
}

export default Layout;